---
- hosts: 155.54.225.133
  sudo: yes
  vars_files:
  - vars.yml
  tasks:
# INSTALL REQUIRED SERVICES

  - name: Install necessary services
    action: apt update_cache=yes name={{ item }} state=latest
    with_items:
    - "python-mysqldb"
    - "mysql-client-5.5"
    - "mysql-server"
    - "nginx-full"
    - "redis-server"
    - "git"
    - "libmysqlclient-dev"
    - "postfix"
    - "imagemagick"

  - name: create .my.cnf file
    copy: src=.my.cnf dest=~/.my.cnf

  - name: copy openvdi_production database
    copy: src=openvdi_production.sql dest=/tmp
  - name: create openvdi_production database
    mysql_db: login_user=root login_password={{ mysql_root_password }} name=mysql state=import target=/tmp/openvdi_production.sql
  - name: update mysql root password for all root accounts
    mysql_user: login_user=root login_password={{ mysql_root_password }} name=root host={{ item }} priv=*.*:ALL,GRANT password={{ mysql_root_password }}
    with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
#    - %

  - name: create db user
    mysql_user: login_user=root login_password={{ mysql_root_password }} name=openvdi host={{ item }} priv=openvdi_production.*:SELECT,INSERT,UPDATE,DELETE password={{ mysql_openvdi_password }}
    with_items:                                                             
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
#    - %

#  - name: allow remote access
#    action: shell sed 's/127.0.0.1/{{ ip_mysql_server }}/g' /etc/mysql/my.cnf > /etc/mysql/my2.cnf

#  - name: rename my2.cnf
#    action: shell mv /etc/mysql/my2.cnf /etc/mysql/my.cnf
   
  - service: name=mysql state=started

  - name: create user openvdi and add to groups adm & sudo
    user: name=openvdi password={{ user_openvdi_password }} shell=/bin/bash groups=adm,sudo append=yes
  - name: ensure .ssh directory is created
    file: path=/home/openvdi/.ssh state=directory
  - name: copy cert
    copy: src=~/.ssh/id_rsa.pub dest=/home/openvdi/.ssh/authorized_keys owner=openvdi group=openvdi
  
  - name: create broker directory
    file: path=/var/www/openvdi state=directory owner=openvdi group=openvdi mode=0755

  - name: ensure broker/config directory is created
    file: path=/var/www/openvdi/broker/config state=directory
  
  - name: create file database.yml
    copy: src=database.yml dest=/var/www/openvdi/broker/config/database.yml owner=root group=root mode=0644

  - name: create applet directory
    file: path=/var/www/openvdi/broker/public/applet state=directory owner=openvdi group=openvdi mode=0755

  - name: copy applet
    copy: src=appletvdi.jar dest=/var/www/openvdi/broker/public/applet/appletvdi.jar owner=openvdi group=openvdi mode=0644
  - name: ensure nginx ssl directory is created
    file: path=/etc/nginx/ssl state=directory

  - name: ensure nginx ssl certificate and key are created
    copy: src=ssl-certs/{{ item }} dest=/etc/nginx/ssl/{{ item }} mode=0600
    with_items:
    - "sslcert.crt"
    - "sslkey.key"
  - service: name=nginx state=reloaded

  - name: ensure the default site is removed
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: ensure sites-available is configured
    copy: src=openvdi.conf dest=/etc/nginx/sites-available/openvdi.conf group=root owner=root
  - service: name=nginx state=reloaded

  - name: ensure sites-available is symlinked to sites-enabled
    file: src=/etc/nginx/sites-available/openvdi.conf dest=/etc/nginx/sites-enabled/openvdi.conf state=link

  - service: name=nginx state=started

  - name: create openvdi service script
    copy: src=openvdi dest=/etc/init.d/openvdi owner=root group=root mode=0755
  
#  - name: ensure sudoers is removed
#    file: path=/etc/sudoers state=absent

  - name: create new sudoers
    copy: src=sudoers dest=/etc owner=root group=root mode=0440

  - name: enable service openvdi autostart
    file: src=/etc/init.d/openvdi dest=/etc/rc2.d/S99openvdi state=link
  - service: name=openvdi state=started

#  - name: create openvdi user
#    shell: adduser openvdi
#  - name: add openvdi user to adm group
#    shell: adduser openvdi adm
#  - name: add openvdi user to sudo group
#    shell: adduser openvdi sudo

- hosts: 155.54.225.133
#  sudo: yes
  remote_user: openvdi
  vars_files:
  - vars.yml
  tasks:
# INSTALL RUBY 2.0
  - shell: \curl -sSL https://get.rvm.io | bash -s stable
  - shell: . /home/openvdi/.rvm/scripts/rvm
  - shell: rvm install 2.0

  - name: no check server certificate
    shell: sed -i 's/sslVerify = true/sslVerify = false/' /~/.gitconfig

- hosts: 155.54.225.133
  sudo: yes
  vars_files: 
  - vars.yml
  tasks:
# CONFIGURE RUBY
  - command: chdir=/var/www/openvdi/broker bundle install
  - command: chdir=/var/www/openvdi/broker RAILS_ENV=production bundle exec rake assets:precompile
  - command: chdir=/var/www/openvdi/broker RAILS_ENV=production bundle exec rake db:migrate
  - command: chdir=/var/www/openvdi/broker RAILS_ENV=production bundle exec rake db:seed

  - service: name=nginx state=restarted
  - service: name=openvdi state=restarted

  - name: create crontab for user openvdi
    copy: src=crontab_openvdi dest=/home/openvdi/.crontab_openvdi
  - shell: crontab -u openvdi /home/openvdi/.crontab_openvdi
  
#  - name: set up authorized keys for the openvdi user
#    shell: ssh-keygen -t rsa
#  - name: generate a 2048-bit SSH key for user openvdi
#    user: name=openvdi generate_ssh_key=yes ssh_key_bits=2048
#    authorized_key: user=openvdi key={{ item }}
#    with_items:
#    - ~/.ssh/id_rsa.pub
